#!/bin/bash
#
docker stop influxdb
docker rm influxdb
docker run -p 8086:8086 \
	-d \
	-v $(pwd)/influxdb.conf:/etc/influxdb/influxdb.conf:ro \
	--name=influxdb \
	influxdb:1.3.6 \
	-config /etc/influxdb/influxdb.conf
